ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/cors-allow-origin: http://localhost:3000, https://*.int.demo.catena-x.net
  tls: 
    - secretName: tls-secret
      hosts:
        - portal-backend.int.demo.catena-x.net
  hosts:
    - host: portal-backend.int.demo.catena-x.net
      paths:
        - path: /api/registration
          pathType: Prefix
          backend:
            service: registration-service
            port: 8080
        - path: /api/administration
          pathType: Prefix
          backend:
            service: administration-service
            port: 8080
        - path: /api/notification
          pathType: Prefix
          backend:
            service: notification-service
            port: 8080
        - path: /api/provisioning
          pathType: Prefix
          backend:
            service: provisioning-service
            port: 8080
        - path: /api/apps
          pathType: Prefix
          backend:
            service: marketplace-app-service
            port: 8080

postgresql:
  secret:
    password: "<path:portal/data/int/postgres#postgres-password>"
    replicationPassword: "<path:portal/data/int/postgres#replication-password>"
    initUserDbSql: "<path:portal/data/int/postgres-db-user#01-init-user-db.sql>"

registration:
  image:
    registrationtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/int/registration#appsettings.json>"

administration:
  image:
    administrationtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/int/administration#appsettings.json>"

provisioning:
  image:
    provisioningtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/int/provisioning#appsettings.json>"

appmarketplace:
  image:
    appmarketplacetag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/int/appmarketplace#appsettings.json>"

portalmigrations:
  image:
    portalmigrationstag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/int/portal-migrations#appsettings.json>"

portalmaintenance:
  image:
    portalmaintenancetag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/int/portal-maintenance#appsettings.json>"

notification:
  image:
    notificationtag: int-v0.5.1
  secret:
    appsettings: "<path:portal/data/int/notification#appsettings.json>"

pgadmin4:
  enabled: true
  secret:
    password: "<path:portal/data/int/pgadmin4#password>"
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.int.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.int.demo.catena-x.net
        secretName: tls-secret