name: portal-backend
portContainer: 8080
portService: 8080
replicaCount: 1
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: ["ALL"]

ingress:
  enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: secret-postgres-init
  secret:
    password: ""
    replicationPassword: ""
    initUserDbSql: ""
  architecture: replication
  audit:
    pgAuditLog: write, ddl
    logLinePrefix: "%m %u %d "
 
registration:
  name: registration-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_registration-service
    tag: int-v0.6.0
  secret:
    name: secret-registration
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

administration:
  name: administration-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_administration-service
    tag: int-v0.6.0
  secret:
    name: secret-administration
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

provisioning:
  name: provisioning-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_provisioning-service
    tag: int-v0.6.0
  secret:
    name: secret-provisioning
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

appmarketplace:
  name: marketplace-app-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_marketplace-app-service
    tag: int-v0.6.0
  secret:
    name: secret-appmarketplace
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

portalmigrations:
  name: portal-migrations
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_portal-migrations
    tag: int-v0.6.0
  secret:
    name: secret-portal-migrations
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

portalmaintenance:
  name: portal-maintenance
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_maintenance-service
    tag: int-v0.6.0
  secret:
    name: secret-portal-maintenance
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

notification:
  name: notification-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_notification-service
    tag: int-v0.6.0
  secret:
    name: secret-notification
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

services:
  name: services-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_services-service
    tag: int-v0.6.0
  secret:
    name: secret-services
    appsettings: "<path:portal/data/pen/services#appsettings.json>"

pgadmin4:
  enabled: false
  ingress:
    enabled: false
