name: "portal"
domain: "demo.catena-x.net"
issuer: "letsencrypt-prod"
portContainer: 8080
portService: 8080
replicaCount: 1

portal:
  path: "/(.*)"
  name: "portal"
  image: "ghcr.io/catenax-ng/product-portal-frontend:0.3.5"
  
registration:
  path: "/registration/(.*)"
  name: "registration"
  image: "ghcr.io/catenax-ng/product-portal-frontend-registration:0.3.5"
