domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: dev_0be80491cc95f6d8f89101b8b2f9ac06af2c9c85

assets:
  image: "ghcr.io/catenax-ng/product-portal-common-assets:dev"

registration:
  image: "ghcr.io/catenax-ng/product-portal-frontend-registration:dev"

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
