name: "portal-pen"
domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: main

assets:
  image: "ghcr.io/catenax-ng/product-portal-common-assets:main"

registration:
  image:
    registrationtag: main

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
