domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: dev_0f75d77dc2877988e9d1398bdac86a24d8e878c6

assets:
  image:
    assetstag: main_0270b670d8b472ec48a0bc31b8f566b1896bcdcc

registration:
  image:
    registrationtag: main_2edd449d94a2dd44199f7eac53489471971e4633

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
