domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: dev_6d67f5d096807e34c16060da85838100c169467f

assets:
  image:
    assetstag: main_0270b670d8b472ec48a0bc31b8f566b1896bcdcc

registration:
  image:
    registrationtag: main_2edd449d94a2dd44199f7eac53489471971e4633

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
