domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: main_1ec047b94a1b2f63198c199d281681a96e77805b

assets:
  image:
    assetstag: main_01a27650e4f1f93b87c2e1688ea71b9e3c44347b

registration:
  image:
    registrationtag: main_2edd449d94a2dd44199f7eac53489471971e4633

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
