domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: dev_0a1a94e185ca9438857c9c99b5e47f875e0268c9

assets:
  image:
    assetstag: main_0270b670d8b472ec48a0bc31b8f566b1896bcdcc

registration:
  image:
    registrationtag: main_2edd449d94a2dd44199f7eac53489471971e4633

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
