domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: $GITHUB_REF_7561c3d5ce7aba22cd7bde07829501c89f709e3a

assets:
  image: "ghcr.io/catenax-ng/product-portal-common-assets:dev"

registration:
  image: "ghcr.io/catenax-ng/product-portal-frontend-registration:dev"

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
