name: "portal"
domain: "demo.catena-x.net"
issuer: "letsencrypt-prod"

frontend:
  portContainer: 8080
  portService: 5000
  replicaCount: 1

  portal:
    path: "/(.*)"
    name: "portal"
    image: "ghcr.io/catenax-ng/product-portal-frontend:0.0.1"

  registration:
    path: "/(landing|registration)"
    name: "registration"
    image: "ghcr.io/catenax-ng/product-portal-frontend-registration:main"

backend:
  portContainer: 80
  portService: 8080
  replicaCount: 1

  registration:
    name: "registration-service"
    image: "ghcr.io/catenax-ng/product-portal-backend_registration-service:main"

  useradministration:
    name: "useradministration-service"
    image: "ghcr.io/catenax-ng/product-portal-backend_useradministration-service:main"

  provisioning:
    name: "provisioning-service"
    image: "ghcr.io/catenax-ng/product-portal-backend_provisioning-service:main"