apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.portalmigrations.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.portalmigrations.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.portalmigrations.name }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.portalmigrations.name }}
        image: {{ .Values.portalmigrations.image }}
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.portContainer }}
        volumeMounts:
        - name: secrets
          mountPath: /migrations/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ .Values.portalmigrations.secret.name }}
