apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.portalmigrations.name }}
  annotations:
  "helm.sh/hook": post-install
  "helm.sh/hook-weight": "-5"
  "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.portalmigrations.name }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.portalmigrations.name }}
        image: {{ .Values.portalmigrations.image }}
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.portContainer }}
        volumeMounts:
        - name: secrets
          mountPath: /migrations/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ .Values.portalmigrations.secret.name }}
