apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.postgresql.secret.pathinitadditionaldbuser }}
  name: secret-postgres-init-additional-db-user
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  01-init-user-db.sql: <01-init-user-db.sql>