apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: portal/data/dev/pgadmin4
  name: secret-pgadmin4
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: <password>