domain: dev.demo.catena-x.net
corsOrigins: http://localhost:3000, https://*.dev.demo.catena-x.net

postgresql:
  secret:
    pathinit: portal/data/dev/postgres
    pathinitdbuser: portal/data/dev/postgres-db-user

registration:
  image:
    registrationtag: 0a577951594f23e4ef066b513b624d796d4fc2d9
  secret:
    path: portal/data/dev/registration

administration:
  image:
    administrationtag: 6f8372592317748d503e31c592a27fb9ecd6cd7b
  secret:
    path: portal/data/dev/administration

provisioning:
  image:
    provisioningtag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/provisioning

appmarketplace:
  image:
    appmarketplacetag: a5663eca11f572f17a1470734b0889ff38ff3143
  secret:
    path: portal/data/dev/appmarketplace

portalmigrations:
  image:
    portalmigrationstag: ad06c898d8219e4078cc7bd203341aa1cf62ee63
  secret:
    path: portal/data/dev/portal-migrations

portalmaintenance:
  image:
    portalmaintenancetag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/portal-maintenance

notification:
  image:
    notificationtag: 33d9a07399d441dc1b26e9bb329dc91634dd56c4
  secret:
    path: portal/data/dev/notification

pgadmin4:
  enabled: true
  secret:
    path: portal/data/dev/pgadmin4
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.dev.demo.catena-x.net
        secretName: portal-pgadmin4.dev.demo.catena-x.net-tls