name: portal-backend-pen

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: http://localhost:3000, https://*.dev.demo.catena-x.net
  tls: 
    - secretName: portal-backend-pen.dev.demo.catena-x.net-tls
      hosts:
        - portal-backend-pen.dev.demo.catena-x.net
  hosts:
    - host: portal-backend-pen.dev.demo.catena-x.net
      paths:
        - path: /api/registration
          pathType: Prefix
          backend:
            service:
              name: registration-service
              port:
                number: 8080
        - path: /api/administration
          pathType: Prefix
          backend:
            service:
              name: administration-service
              port:
                number: 8080
        - path: /api/notification
          pathType: Prefix
          backend:
            service:
              name: notification-service
              port:
                number: 8080
        - path: /api/provisioning
          pathType: Prefix
          backend:
            service:
              name: provisioning-service
              port:
                number: 8080
        - path: /api/apps
          pathType: Prefix
          backend:
            service:
              name: marketplace-app-service
              port:
                number: 8080

postgresql:
  secret:
    pathinit: portal/data/pen/postgres
    pathinitdbuser: portal/data/pen/postgres-db-user

registration:
  image:
    registrationtag: latest
  secret:
    path: portal/data/pen/registration

administration:
  image:
    administrationtag: 3e2f9c1e86b06ec98063dd9f68af06f6789e466e
  secret:
    path: portal/data/pen/administration

provisioning:
  image:
    provisioningtag: latest
  secret:
    path: portal/data/pen/provisioning

appmarketplace:
  image:
    appmarketplacetag: latest
  secret:
    path: portal/data/pen/appmarketplace

portalmigrations:
  image:
    portalmigrationstag: latest
  secret:
    path: portal/data/pen/portal-migrations

portalmaintenance:
  image:
    portalmaintenancetag: latest
  secret:
    path: portal/data/pen/portal-maintenance

notification:
  image:
    notificationtag: latest
  secret:
    path: portal/data/pen/notification

pgadmin4:
  enabled: true
  secret:
    path: portal/data/pen/pgadmin4
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4-pen.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4-pen.dev.demo.catena-x.net
        secretName: portal-pgadmin4-pen.dev.demo.catena-x.net-tls