domain: "demo.catena-x.net"
issuer: "letsencrypt-prod"
name: "portal-backend"
portContainer: 80
portService: 8080
replicaCount: 1
postgresql:
  enabled: true
  auth:
    username: portal
    password: ""
    database: postgres
    existingSecret: ""
  architecture: replication
  primary:
    initdb:
      scriptsConfigMap: p-init-sql

registration:
  name: "registration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_registration-service:latest"
  secret:
    name: "secret-registration"
    path: "portal/data/int/registration"

useradministration:
  name: "useradministration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_useradministration-service:latest"

provisioning:
  name: "provisioning-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_provisioning-service:latest"

appmarketplace:
  name: "marketplace-app-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_marketplace-app-service:latest"