domain: dev.demo.catena-x.net
corsOrigins: http://localhost:3000, https://*.dev.demo.catena-x.net

postgresql:
  secret:
    pathinit: portal/data/dev/postgres
    pathinitdbuser: portal/data/dev/postgres-db-user

registration:
  image:
    registrationtag: 1336b2f662b18844baf854e6c8e07a67e2393ba3
  secret:
    path: portal/data/dev/registration

administration:
  image:
    administrationtag: 3e2f9c1e86b06ec98063dd9f68af06f6789e466e
  secret:
    path: portal/data/dev/administration

provisioning:
  image:
    provisioningtag: d7d147804bd8e1dd98f34201d719b3927c688a55
  secret:
    path: portal/data/dev/provisioning

appmarketplace:
  image:
    appmarketplacetag: 6cb736f785dbb4bbebc111677e1d1be356528820
  secret:
    path: portal/data/dev/appmarketplace

portalmigrations:
  image:
    portalmigrationstag: e37891e2fb690ef9560fbb1abb8e3b6a2f2a5319
  secret:
    path: portal/data/dev/portal-migrations

portalmaintenance:
  image:
    portalmaintenancetag: e37891e2fb690ef9560fbb1abb8e3b6a2f2a5319
  secret:
    path: portal/data/dev/portal-maintenance

notification:
  image:
    notificationtag: 1c2eb021e1ed38ad820b581f9ef10016b58e6cd6
  secret:
    path: portal/data/dev/notification

pgadmin4:
  enabled: true
  secret:
    path: portal/data/dev/pgadmin4
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.dev.demo.catena-x.net
        secretName: portal-pgadmin4.dev.demo.catena-x.net-tls