domain: "int.demo.catena-x.net"
issuer: "letsencrypt-prod"
name: "portal-backend"
portContainer: 80
portService: 8080
replicaCount: 1
postgresql:
  enabled: true
  auth:
    username: portal
    password: ""
    database: postgres
    existingSecret: ""
  architecture: replication
  primary:
    initdb:
      scriptsConfigMap: p-init-sql

registration:
  name: "registration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_registration-service:latest"
  secret:
    name: "secret-registration"
    path: "portal/data/int/registration"

administration:
  name: "administration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_administration-service:latest"
  secret:
    name: "secret-administration"
    path: "portal/data/int/administration"

provisioning:
  name: "provisioning-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_provisioning-service:latest"
  secret:
    name: "secret-provisioning"
    path: "portal/data/int/provisioning"

appmarketplace:
  name: "marketplace-app-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_marketplace-app-service:latest"
  secret:
    name: "secret-appmarketplace"
    path: "portal/data/int/appmarketplace"