domain: dev.demo.catena-x.net
corsOrigins: http://localhost:3000, https://*.dev.demo.catena-x.net

postgresql:
  secret:
    pathinit: portal/data/dev/postgres
    pathinitdbuser: portal/data/dev/postgres-db-user

registration:
  image:
    registrationtag: latest
  secret:
    path: portal/data/dev/registration

administration:
  image:
    administrationtag: 3e2f9c1e86b06ec98063dd9f68af06f6789e466e
  secret:
    path: portal/data/dev/administration

provisioning:
  image:
    provisioningtag: latest
  secret:
    path: portal/data/dev/provisioning

appmarketplace:
  image:
    
  secret:
    path: portal/data/dev/appmarketplace

portalmigrations:
  image:
    portalmigrationstag: latest
  secret:
    path: portal/data/dev/portal-migrations

portalmaintenance:
  image:
    portalmaintenancetag: 5b2034fbfea6f68601fecaefa1a5156302eff60a
  secret:
    path: portal/data/dev/portal-maintenance

notification:
  image:
    notificationtag: latest
  secret:
    path: portal/data/dev/notification

pgadmin4:
  enabled: true
  secret:
    path: portal/data/dev/pgadmin4
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.dev.demo.catena-x.net
        secretName: portal-pgadmin4.dev.demo.catena-x.net-tls