domain: "int.demo.catena-x.net"
corsOrigins: "http://localhost:3000, https://*.int.demo.catena-x.net"
issuer: "letsencrypt-prod"
name: "portal-backend"
portContainer: 80
portService: 8080
replicaCount: 1

postgresql:
  enabled: true
  auth:
    username: portal
    database: postgres
    existingSecret: secret-postgres-init
  secret:
    name: "secret-postgres-init"
    path: "portal/data/int/postgres"
  architecture: replication
  primary:
    initdb:
      scriptsConfigMap: p-init-sql
pgadmin4:
  existingSecret: secret-pgadmin4
  secret:
    name: "secret-pgadmin4"
    path: "portal/data/int/pgadmin4"
  # ingress:
  #   enabled: true
    # annotations:
    #   cert-manager.io/cluster-issuer: letsencrypt-prod
    #   kubernetes.io/ingress.class: nginx
    # hosts:
    #   - host: "portal-backend.int.demo.catena-x.net"
    #     paths:
    #     - path: /pgadmin4
    #       pathType: Prefix
    # tls:
    #   - hosts:
    #     - portal-backend.int.demo.catena-x.net
    #     secretName: portal-backend.int.demo.catena-x.net-tls


registration:
  name: "registration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_registration-service:latest"
  secret:
    name: "secret-registration"
    path: "portal/data/int/registration"

administration:
  name: "administration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_administration-service:latest"
  secret:
    name: "secret-administration"
    path: "portal/data/int/administration"

provisioning:
  name: "provisioning-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_provisioning-service:latest"
  secret:
    name: "secret-provisioning"
    path: "portal/data/int/provisioning"

appmarketplace:
  name: "marketplace-app-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_marketplace-app-service:latest"
  secret:
    name: "secret-appmarketplace"
    path: "portal/data/int/appmarketplace"