domain: "demo.catena-x.net"
issuer: "letsencrypt-prod"
name: "portal-backend"
portContainer: 80
portService: 8080
replicaCount: 1
postgresql:
  enabled: true

registration:
  name: "registration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_registration-service:main"

useradministration:
  name: "useradministration-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_useradministration-service:main"

provisioning:
  name: "provisioning-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_provisioning-service:main"

appmarketplace:
  name: "marketplace-app-service"
  image: "ghcr.io/catenax-ng/product-portal-backend_marketplace-app-service:main"