ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: http://localhost:3000, https://*.dev.demo.catena-x.net
  tls: 
    - secretName: portal-backend.dev.demo.catena-x.net-tls
      hosts:
        - portal-backend.dev.demo.catena-x.net
  hosts:
    - host: portal-backend.dev.demo.catena-x.net
      paths:
        - path: /api/registration
          pathType: Prefix
          backend:
            service:
              name: registration-service
              port:
                number: 8080
        - path: /api/administration
          pathType: Prefix
          backend:
            service:
              name: administration-service
              port:
                number: 8080
        - path: /api/notification
          pathType: Prefix
          backend:
            service:
              name: notification-service
              port:
                number: 8080
        - path: /api/provisioning
          pathType: Prefix
          backend:
            service:
              name: provisioning-service
              port:
                number: 8080
        - path: /api/apps
          pathType: Prefix
          backend:
            service:
              name: marketplace-app-service
              port:
                number: 8080

postgresql:
  secret:
    pathinit: portal/data/dev/postgres
    pathinitdbuser: portal/data/dev/postgres-db-user

registration:
  image:
    registrationtag: 6f1507d4134af08895d31694042f75256bccb80b
  secret:
    path: portal/data/dev/registration

administration:
  image:
    administrationtag: 6f1507d4134af08895d31694042f75256bccb80b
  secret:
    path: portal/data/dev/administration

provisioning:
  image:
    provisioningtag: ac720752399754d95999b561c414578b5e13ca40
  secret:
    path: portal/data/dev/provisioning

appmarketplace:
  image:
    appmarketplacetag: ac720752399754d95999b561c414578b5e13ca40
  secret:
    path: portal/data/dev/appmarketplace

portalmigrations:
  image:
    portalmigrationstag: ad06c898d8219e4078cc7bd203341aa1cf62ee63
  secret:
    path: portal/data/dev/portal-migrations

portalmaintenance:
  image:
    portalmaintenancetag: ac720752399754d95999b561c414578b5e13ca40
  secret:
    path: portal/data/dev/portal-maintenance

notification:
  image:
    notificationtag: ac720752399754d95999b561c414578b5e13ca40
  secret:
    path: portal/data/dev/notification

pgadmin4:
  enabled: true
  secret:
    path: portal/data/dev/pgadmin4
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.dev.demo.catena-x.net
        secretName: portal-pgadmin4.dev.demo.catena-x.net-tls