ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
  tls: 
    - secretName: tls-secret
      hosts:
        - portal.dev.demo.catena-x.net
  hosts:
    - host: portal.dev.demo.catena-x.net
      paths:
        - path: "/(.*)"
          pathType: Prefix
          backend:
            service: "portal"
            port: 8080
        - path: "/registration/(.*)"
          pathType: Prefix
          backend:
            service: "registration"
            port: 8080
        - path: "/((assets|swagger)/.*)"
          pathType: Prefix
          backend:
            service: "assets"
            port: 8080
        - path: "/demonstrator/(.*)"
          pathType: Prefix
          backend:
            service: "demonstrator"
            port: 8080

portal:
  image:
    portaltag: dev_e5f40e4950beeff27507fc1001f5cf6c22b4777c

assets:
  image:
    assetstag: main_5d48fd115edf9770b69e73e09e14afd52f70d786

registration:
  image:
    registrationtag: dev_13d683bd12daad6a505c6f952ab29d192182214c

demonstrator:
  enabled: true
  name: "demonstrator"
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
