name: "portal-pen"
domain: "dev.demo.catena-x.net"

portal:
  image:
    portaltag: main

assets:
  image:
    assetstag: main

registration:
  image:
    registrationtag: main

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
