ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
  tls: 
    - secretName: tls-secret
      hosts:
        - portal.dev.demo.catena-x.net
  hosts:
    - host: portal.dev.demo.catena-x.net
      paths:
        - path: "/(.*)"
          pathType: Prefix
          backend:
            service: "portal"
            port: 8080
        - path: "/registration/(.*)"
          pathType: Prefix
          backend:
            service: "registration"
            port: 8080
        - path: "/((assets|swagger)/.*)"
          pathType: Prefix
          backend:
            service: "assets"
            port: 8080
        - path: "/demonstrator/(.*)"
          pathType: Prefix
          backend:
            service: "demonstrator"
            port: 8080

portal:
  image:
    portaltag: main_7149939d689fe157120ba3c3f9c9ba90b7f2eece

assets:
  image:
    assetstag: main_65cb76dc0df96c795fd21041966140683a7c55ea

registration:
  image:
    registrationtag: main_046a59c21d9cd51b75bbbace052a83e80c6dcd75

demonstrator:
  enabled: true
  name: "demonstrator"
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
