name: "portal-pen"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
  tls: 
    - secretName: tls-secret
      hosts:
        - portal-pen.dev.demo.catena-x.net
  hosts:
    - host: portal-pen.dev.demo.catena-x.net
      paths:
        - path: "/(.*)"
          pathType: Prefix
          frontend:
            service: "portal"
            port: 8080
        - path: "/registration/(.*)"
          pathType: Prefix
          frontend:
            service: "registration"
            port: 8080
        - path: "/((assets|swagger)/.*)"
          pathType: Prefix
          frontend:
            service: "assets"
            port: 8080

portal:
  image:
    portaltag: main

assets:
  image:
    assetstag: main

registration:
  image:
    registrationtag: main

demonstrator:
  enabled: false
