name: "portal"
portContainer: 8080
portService: 8080
replicaCount: 1
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true

ingress:
  enabled: false

portal:
  name: "portal"
  image:
    name: "ghcr.io/catenax-ng/product-portal-frontend"
    portaltag: 0.6.0

assets:
  name: "assets"
  image:
    name: "ghcr.io/catenax-ng/product-portal-common-assets"
    assetstag: 0.6.0

registration:
  name: "registration"
  image: 
    name: "ghcr.io/catenax-ng/tx-portal-frontend-registration"
    registrationtag: 0.6.0

demonstrator:
  enabled: false
