ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
  tls: 
    - secretName: tls-secret
      hosts:
        - portal.dev.demo.catena-x.net
  hosts:
    - host: portal.dev.demo.catena-x.net
      paths:
        - path: "/(.*)"
          pathType: Prefix
          backend:
            service: "portal"
            port: 8080
        - path: "/registration/(.*)"
          pathType: Prefix
          backend:
            service: "registration"
            port: 8080
        - path: "/((assets|swagger)/.*)"
          pathType: Prefix
          backend:
            service: "assets"
            port: 8080
        - path: "/demonstrator/(.*)"
          pathType: Prefix
          backend:
            service: "demonstrator"
            port: 8080

portal:
  image:
    portaltag: dev_415bf82988633967c9d15be025688378c7132036

assets:
  image:
    assetstag: main_55b2f3a1b93afe4af4877aa919ec645f9689ac14

registration:
  image:
    registrationtag: main_cdddf1c1b048140cf0962e0817aa00866fa6bb6f

demonstrator:
  enabled: true
  name: "demonstrator"
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
