ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
  tls: 
    - secretName: tls-secret
      hosts:
        - portal.dev.demo.catena-x.net
  hosts:
    - host: portal.dev.demo.catena-x.net
      paths:
        - path: "/(.*)"
          pathType: Prefix
          backend:
            service: "portal"
            port: 8080
        - path: "/registration/(.*)"
          pathType: Prefix
          backend:
            service: "registration"
            port: 8080
        - path: "/((assets|swagger)/.*)"
          pathType: Prefix
          backend:
            service: "assets"
            port: 8080
        - path: "/demonstrator/(.*)"
          pathType: Prefix
          backend:
            service: "demonstrator"
            port: 8080

portal:
  image:
    portaltag: dev_e6640bc350551ad181a01c0a2cff98af49b5cbc0

assets:
  image:
    assetstag: main_7e7e2dea72d56e410ee44dd9141ad87b51c34a76

registration:
  image:
    registrationtag: dev_8609bc6d3273bfa9d4ee86732dd00821ef96b4fa

demonstrator:
  enabled: true
  name: "demonstrator"
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
