ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
  tls: 
    - secretName: tls-secret
      hosts:
        - portal.dev.demo.catena-x.net
  hosts:
    - host: portal.dev.demo.catena-x.net
      paths:
        - path: "/(.*)"
          pathType: Prefix
          backend:
            service: "portal"
            port: 8080
        - path: "/registration/(.*)"
          pathType: Prefix
          backend:
            service: "registration"
            port: 8080
        - path: "/((assets|swagger)/.*)"
          pathType: Prefix
          backend:
            service: "assets"
            port: 8080
        - path: "/demonstrator/(.*)"
          pathType: Prefix
          backend:
            service: "demonstrator"
            port: 8080

portal:
  image:
    portaltag: dev_935aeb57fcff01a79b346f2054ac8a1b89836b55

assets:
  image:
    assetstag: main_d7754292b1f170644c83f11c03c1b6ed58fa0978

registration:
  image:
    registrationtag: dev_4b3a42526247af0285c2376c222f9d6abff3042c

demonstrator:
  enabled: true
  name: "demonstrator"
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
