name: Portal InitDB

on: 
  push:
    paths:
      # this workflow file
      - '.github/workflows/portal-initdb.yml'
      # Docker files
      - 'docker/Dockerfile.import'
      # sqls
      - 'import/**'

#TODO: Comment in, as soon as it works in hotel budapest
    branches:
      # Integration environment
     - main
     - feature/add_db_user_update_sqls
  workflow_dispatch:

jobs:
  build:
    # name of the job starts with a "run-level" subordinate to the workflow such that we can
    # depend on them in order to implement workflow dependencies
    name: 90 portal-initdb image built
    runs-on: ubuntu-latest
    # rely on the first job
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}_initdb

    steps:
      # Get the latest sources
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push KeyCloak custom images for central and shared idp instances
      - name: 'Build images'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.import
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
