name: Auto-image-update Registration-Service

on:
  workflow_dispatch:
    inputs:
      new-image:
        description: 'new available image'
        required: true
        default: 'no content'

env:
  IMAGE_BEGINN: 'registrationtag: '
  IMAGE_FULL_NEW: 'registrationtag: ${{ inputs.new-image }}'

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify image tag in values-dev.yaml
        run: |
          sed -i 's/${{ env.IMAGE_BEGINN }}.*/${{ env.IMAGE_FULL_NEW }}/' chart/portal-backend/values-dev.yaml

      - name: Commit and push updated values-dev.yaml
        run: bash ./scripts/commit-push.sh
